### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ihorkatkov** [fremantle-capital/tai#44]
Hey. First of all, thanks for a great library :)

I'm going to experiment with it, but before want to ask some questions
- Are you use it in production?
- Are there any possibilities for backtesting?
- How is it handles rate limiting?
- Any plans for `Dead men's switch` functionality or is it possible to implement is as an advisor?

Best,
Ihor

**Comment by rupurt** [comment]
Hi @ihorkatkov,

Let me know what kind of problems you run into along the way with your experiments.

* It is working against production exchanges
* There is no backtesting adapter but you can write unit tests using the mock venue adapter to test your strategies. A backtesting adapter is on the todo list one day but I have many other priorities ahead of it currently.
* Rate limiting is handled within the advisor by storing the required information in the `run_store`. There is no explicit framework support for it at this point but is something I would like to add
* There are [plans to cleanly shutdown an advisor](https://github.com/fremantle-capital/tai/projects/1#card-16261425) (e.g. cancel orders) but not a dead mans switch explicity
